### ISSUE TITLE
Service database not found! serviceLOG.db empty

### ISSUE THREAD

**Issue by LovelyA72** [ew8bak/ewlog#16]
![image](https://github.com/ew8bak/ewlog/assets/29054052/51dd0a0c-b19c-470f-98ab-fe5234b17a85)
When I run the software I got this error. After that the software creates an empty serviceLOG.db with zero data (0B) in it.

I built the software with Lazarus 3.0 RC2

**Comment by ew8bak** [comment]
https://github.com/ew8bak/ewlog/tree/master/DataBases
copy to bin

**Comment by LovelyA72** [comment]
Thank you so much! I can't believe I missed it
